### ISSUE TITLE
Screen rotation show a pixel drawing issue

### ISSUE THREAD

**Issue by sumotoy** [sumotoy/OLED_SSD1332#2]
This problem it's related to the other issue I've recently found and will be fixed soon.

**Comment by fxmech** [comment]
I was having problems with screen rotation where in portrait mode, the text was mirrored
I modified this to get it to work:


void OLED_SSD1332::setRotation(uint8_t x) {
  rotation = (x & 3);
  switch(rotation) {
   case 0:
		_width  = WIDTH;
		_height = HEIGHT;
		bitClear(_remapData,4);
		break;
   case 1:
		_width  = HEIGHT;
		_height = WIDTH;
		bitSet(_remapData,1);
		break;
   case 2:
		_width  = WIDTH;
		_height = HEIGHT;
		bitSet(_remapData,4);
		break;
   case 3:
		_width  = HEIGHT;
		_height = WIDTH;
		bitClear(_remapData,1);
		break;
  }
  setRegister(_CMD_SETREMAP,_remapData);
}

/*
0: fixed:Normal - pixel:0 it's the bottom, 1 it's the top
1: fixed:Text mirrored
2: fixed:Not drawing
3: Correct
*/


...hope this helps

**Comment by sumotoy** [comment]
tanks for report this!

**Comment by sumotoy** [comment]
Apllied patch and fixed Teensyduino 1.24 compatibility, thanks again!
